server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: framework

spring:
  application:
    name: ekomobil

  jackson:
    default-property-inclusion: non_null

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ekomobil}
    username: ${DB_USER:burakcoskun}
    password: ${DB_PASS:brkcskn29}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC

  web:
    cors:
      allowed-origin-patterns: >
        http://localhost:*, http://127.0.0.1:*,
        http://172.30.9.225:*, http://172.30.9.225,
        https://app.ekomobil.com
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

  mail:
    default-encoding: UTF-8
    test-connection: false
    properties:
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000
      mail.debug: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    persist-authorization: true
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match: /api/**

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO

app:
  jwt:
    secret: "kK8+o4bq2R9fE5Yw3L1zQ7TnU2hV6mB9sP0rX4cZ8aD1wJ3lN5uG7yK0qR2tV4"
    expiresInMinutes: 10080
  reset:
    base-url: https://app.ekomobil.com/reset
    ttl-minutes: 30
  mail:
    from: "Ekomobil <no-reply@ekomobil.com>"

security:
  dev-auth:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: sendgrid
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
app:
  mail:
    from: "Ekomobil <no-reply@ekomobil.com>"

---
spring:
  config:
    activate:
      on-profile: gmail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
app:
  mail:
    from: "Burak Coskun <burakkcoskun29@gmail.com>"
